language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
install:
   - composer install
   - composer require "satooshi/php-coveralls"
   - phpunit --version
after_success:
  - travis_retry php vendor/bin/coveralls